package jp.co.dosanko.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UserRoles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRoles extends CayenneDataObject {

    public static final String DISPLAY_PROPERTY = "display";
    public static final String NAME_PROPERTY = "name";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String ROLE_PROPERTY = "role";

    public static final String ID_PK_COLUMN = "ID";

    public void setDisplay(String display) {
        writeProperty("display", display);
    }
    public String getDisplay() {
        return (String)readProperty("display");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setRole(String role) {
        writeProperty("role", role);
    }
    public String getRole() {
        return (String)readProperty("role");
    }

}
